<?php  include("dbconnection.php");  ?>
<?php



				$sql = "insert into safetytip(AppName, Description, Safety_tips, Features, Logo, DateAdded, Remark) 
				 VALUES
('TikTok', 'TikTok is a video-sharing app where users create and share short clips set to music, participate in viral challenges, and express creativity.', 'Set your account to private, and monitor who follows you. Limit interactions to friends and family, and avoid sharing personal information.', 'TikTok offers a Family Pairing feature that allows parents to manage screen time and control content visibility for their teens.', 'tiktok-logo.png'),
('Instagram', 'Instagram allows users to share photos, videos, and stories, making it one of the most visual platforms.', 'Adjust your profile to private, and review follower requests carefully. Use the Close Friends feature for private stories and limit the sharing of personal data.', 'Encourage open conversations about appropriate sharing and interaction on the platform to promote healthy social media habits.', 'instagram-logo.png'),
('Facebook', 'Facebook is a social networking site that allows users to connect with friends, share photos and videos, and post updates.', 'Review privacy settings regularly, and limit the amount of personal information shared publicly. Be cautious of friend requests from unknown users.', 'Facebook provides tools to manage privacy settings, block users, and review your timeline activity.', 'facebook-logo.png'),
('Twitter', 'Twitter is a microblogging platform where users can post and interact with messages known as tweets.', 'Be mindful of the information you share publicly and use privacy settings to control who can see your tweets. Avoid engaging with suspicious accounts.', 'Twitter offers features like blocking users and controlling who can view your tweets through account settings.', 'twitter-logo.png'),
('YouTube', 'YouTube is a video-sharing platform where users can upload, view, and comment on videos.', 'Use parental controls and review content before allowing children to view it. Avoid sharing personal details in video descriptions or comments.', 'YouTube provides features such as Restricted Mode and the ability to block users and report inappropriate content.', 'youtube-logo.png'),
('Snapchat', 'Snapchat is a multimedia messaging app known for its disappearing messages and interactive filters.', 'Be aware of who you are snapping and avoid sharing sensitive content. Use privacy settings to control who can send you snaps and view your stories.', 'Snapchat includes features like privacy settings for stories, the ability to block users, and controls for managing who can view your content.', 'snapchat-logo.png'),
('Reddit', 'Reddit is a discussion platform with forums (subreddits) on various topics where users can post content and participate in discussions.', 'Be cautious when sharing personal information and review your privacy settings. Follow subreddit rules and report any inappropriate behavior.', 'Reddit offers tools for managing privacy settings, blocking users, and moderating content in subreddits.', 'reddit-logo.png'),
('LinkedIn', 'LinkedIn is a professional networking site used to connect with colleagues, share professional updates, and search for job opportunities.', 'Be mindful of the personal information shared on your profile. Adjust privacy settings to control who can view your connections and profile details.', 'LinkedIn provides privacy settings to manage who can view your profile and interactions, as well as tools for controlling visibility of your updates.', 'linkedin-logo.png'),
('Tumblr', 'Tumblr is a microblogging platform that allows users to post multimedia content to a short-form blog.', 'Use privacy settings to control who can view your posts and manage who can comment on or interact with your content.', 'Tumblr provides options for private blogs, customizable privacy settings, and tools for moderating interactions.', 'tumblr-logo.png'),
('WhatsApp', 'WhatsApp is a messaging app that supports text, voice, and video communication.', 'Enable two-step verification and be cautious of sharing sensitive information. Use privacy settings to control who can see your status and profile picture.', 'WhatsApp offers encryption for messages, customizable privacy settings, and the ability to block contacts.', 'whatsapp-logo.png'),
('Viber', 'Viber is a messaging app known for its voice and video calling capabilities.', 'Be cautious about adding unknown contacts and adjust privacy settings to limit who can contact you. Avoid sharing personal information publicly.', 'Viber provides features like end-to-end encryption, customizable privacy settings, and controls for blocking users.', 'viber-logo.png'),
('Discord', 'Discord is a communication platform designed for gamers that offers voice, video, and text chat in various servers.', 'Be mindful of the servers you join and review your privacy settings to control who can message you or view your profile.', 'Discord includes server moderation tools, privacy settings, and options for blocking and reporting users.', 'discord-logo.png'),
('WeChat', 'WeChat is a multi-purpose messaging, social media, and mobile payment app.', 'Review your privacy settings and be cautious when connecting with unknown users. Use the app’s features to control who can see your posts and contact you.', 'WeChat offers privacy settings for managing contacts, posts, and interactions, along with security features for transactions.', 'wechat-logo.png')";

?>
